### ISSUE TITLE
How to override LoginView?

### ISSUE THREAD

**Issue by fessacchiotto** [jazzband/dj-rest-auth#133]
Hello! I need to return a different token serializer response based on the type of user (regular and API user). I think I can do the selection of the serializer by overriding the method `get_response_serializer `in the `LoginView`. My question is: how do I override the LoginView in my code? To override the `LoginSerializer` I've modified the proper setting as in the `dj-rest-auth ` manual, but where should I put my custom `LoginView`? Could you kindly provide a simple example? Many thanks!

**Comment by mohmyo** [comment]
I think the easiest way, for now, is to create your custom `LoginView` class that inherits from `LoginView`, then add a path in urls.py that uses your custom `LoginView `with the same route as the one in dj-rest-auth `urls.py` and that's it.

Example:
```python
path('login/', YourCustomLoginView.as_view(), name='custom_rest_login'),
path('dj-rest-auth/', include('dj_rest_auth.urls'))
```

**Note**: this path should be placed right before the path that includes `dj_rest_auth.urls`, so the first time Django is looking for a matching path for login will use the one you created instead of the one included from `dj_rest_auth.urls`.

In the future, I'm looking forward to the time when overriding views is the same way as overriding serializers

**Comment by fessacchiotto** [comment]
Dear Mahmoud. Very clear explanation! Many thanks. M

**Comment by mohmyo** [comment]
Glad it helped :)
