### ISSUE TITLE
How to change from django-rest-auth to dj-rest-auth ?!

### ISSUE THREAD

**Issue by thomas545** [jazzband/dj-rest-auth#155]
I am using django-rest-auth in my project, I want to replace django-rest-auth with this package how can I do that ??

**Comment by iMerica** [comment]
There isn't really a migration since the API is 1:1.

1) `pip install dj-rest-auth` (and remove the legacy package)
2) Replace the app in `INSTALLED_APPS` 
3) Replace the urls.
4) Update any new configuration settings (see docs).
5) Run all your unit tests in your project to ensure everything works as expected.

**Comment by thomas545** [comment]
> There isn't really a migration since the API is 1:1.
> 
> 1. `pip install dj-rest-auth` (and remove the legacy package)
> 2. Replace the app in `INSTALLED_APPS`
> 3. Replace the urls.
> 4. Update any new configuration settings (see docs).
> 5. Run all your unit tests in your project to ensure everything works as expected.

Thank You, I thought there is another way to replace.
