### ISSUE TITLE
The generated password reset token is not long enough and always having a fixed length

### ISSUE THREAD

**Issue by mohmyo** [jazzband/dj-rest-auth#22]
I have added password_reset_confirm URL into my urls.py as mentioned in docs, inspired by the demo project

```python
re_path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            TemplateView.as_view(),
            name='password_reset_confirm'),
```

Everything is working just fine, but I have a question regarding the token, I expected it to be longer as the one in registration endpoint but I always get something like that:

`/password-reset/confirm/Mw/5f8-8a381855ed4a6cadb9fe/`

So, the first part always has the length of 3 characters and the second one always has the length of 20 characters, so, what is the point of giving it a range if it will always have a fixed length, also why it's not long enough, am I missing something?

**Comment by bugraaydogar** [comment]
Hi Mahmoud,

It seems like, it is the default Django implementation which is also used by the dj-rest-auth as well.
Please have a look at following links to learn more.

https://github.com/django/django/blob/00ff7a44dee91be59a64559cadeeba0f7386fd6f/django/contrib/auth/tokens.py#L17

https://github.com/django/django/blob/00ff7a44dee91be59a64559cadeeba0f7386fd6f/django/contrib/auth/tokens.py#L58

It seems like limitation of 20 characters was done on purpose to shorten the URL.

Hope it helps,
Bugra

**Comment by mohmyo** [comment]
Hey Bugra,

Thanks for posting these links they are really helpful to understand how it really works and it answers that this is not related to dj-rest-auth, I understand the limitations of 20 charters and I have no problem with it, but it still not clear why range variation has no use as the generated token doesn't is fixed somehow, why we give it ranges of {1,13} and {1,20} as the URL above when it's not used?

**Comment by bugraaydogar** [comment]
Hi Mahmoud,

Sorry, I missed that part. To be honest, I do not know the history of Django. But when I check with the blame, I saw that, mentioned code block with ranges are added almost 6 years ago.

Unfortunately, I do not have a proper answer. But, I would assume that, it could be historical reasons.

**Comment by anuj9196** [comment]
From `django.contrib.auth.tokens`, this method is responsible for generating the token used while resetting the password.

```
    def _make_token_with_timestamp(self, user, timestamp):
        # timestamp is number of days since 2001-1-1.  Converted to
        # base 36, this gives us a 3 digit string until about 2121
        ts_b36 = int_to_base36(timestamp)
        hash_string = salted_hmac(
            self.key_salt,
            self._make_hash_value(user, timestamp),
            secret=self.secret,
        ).hexdigest()[::2]  # Limit to 20 characters to shorten the URL.
        return "%s-%s" % (ts_b36, hash_string)
```
The documentation describes why the first part of the token is 3 digit long. Also as per the doc, it is using timestamp to generate token which will give 3 digit token upto 2121, after this time may be the size of the token will get change.

The range in the regex `{1,13}` defines the range of the length of the characters. It means the first half of the token should be at least 1 character or at most 13 character long.

Also since the size is being set manually in the `urls` you can change the values accordingly. This won't have any effect on token generation.

Because regex in the url define what values it should hold. It is not used in generating token or in view.

You can change the url path like
```
path('password/reset/confirm/<uidb64>/<token>', TemplateView.as_view(), name='password_reset_confirm'),
```
And it will work. Note, there is no regex length defined in the above url.

**Comment by mohmyo** [comment]
@anuj9196 Thank you so much!, everything is clear now.
I got this confusion as I thought the above URL is used for reverse so it would follow the exact regex.

Thanks again!

**Comment by mohmyo** [comment]
@bugraaydogar No worries, you helped me too.
All is clear now thanks to @anuj9196
