### ISSUE TITLE
CSRF Login vulnerability for web login (and other unauthenticated post requests)

### ISSUE THREAD

**Issue by ajbeach2** [jazzband/dj-rest-auth#49]
The following test case demonstrates the issue (this test will fail without csrf  checks)
```python
@override_settings(REST_USE_JWT=True)
@override_settings(JWT_AUTH_COOKIE='jwt-auth')
def test_login_csrf(self):
    from rest_framework.test import APIRequestFactory
    from django.contrib.sessions.middleware import SessionMiddleware
    from dj_rest_auth.registration.views import LoginView

    get_user_model().objects.create_user(self.USERNAME, '', self.PASS)
    view = LoginView.as_view()

    def add_session_to_request(request):
        """Annotate a request object with a session"""
        middleware = SessionMiddleware()
        middleware.process_request(request)
        request.session.save()

    factory = APIRequestFactory(enforce_csrf_checks=True)
    request = factory.post(self.login_url, {
        "username": self.USERNAME,
        "password": self.PASS
    })
    add_session_to_request(request)
    response = view(request)
    self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

```

There are 2 issues:
1. the login (and other unauthenticated post) forms have csrf when using  rest_framework.authentication.SessionAuthentication'. 

2. the login (and other unauthenticated post) forms have csrf when using JWTCookieAuthentication

1 can be fixed with using different views for web clients that only use SessionAuthentication. 1 is not possible to fix as a single view because of how drf handles multiple auth backends (see notes below). 

2 can be fixed with the following:
```python
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework import exceptions
from rest_framework.authentication import CSRFCheck
class JWTCookieAuthentication(JWTAuthentication):
    """
    An authentication plugin that hopefully authenticates requests through a JSON web
    token provided in a request cookie (and through the header as normal, with a
    preference to the header).
    """
    def enforce_csrf(self, request):
        """
        Enforce CSRF validation for session based authentication.
        """
        check = CSRFCheck()
        # populates request.META['CSRF_COOKIE'], which is used in process_view()
        check.process_request(request)
        reason = check.process_view(request, None, (), {})
        if reason:
            # CSRF failed, bail with explicit error message
            raise exceptions.PermissionDenied('CSRF Failed: %s' % reason)

    def authenticate(self, request):
        from django.conf import settings
        cookie_name = getattr(settings, 'JWT_AUTH_COOKIE', None)
        header = self.get_header(request)
        self.enforce_csrf(request)
        if header is None:
            if cookie_name:
                raw_token = request.COOKIES.get(cookie_name)
            else:
                return None
        else:
            raw_token = self.get_raw_token(header)

        if raw_token is None:
            return None

        validated_token = self.get_validated_token(raw_token)
        return self.get_user(validated_token), validated_token
```
Django rest framework explicitly disables csrf checks for unauthenticated post requests because of the way django rest works with multiple authentication classes, ie, if you have both Session and Token auth classes for the same login view, its not possible to enforce csrf on login with breaking the Token auth; clients that use token auth may not be web clients and wouldn't have the csrf vulnerability because they are not using cookies. 

The built in django login views (django.admin.contrib.auth.views) all enforce csrf on login and other unauthenticated post requests.

The django rest framework recommends using django's login forms for this reason: 
https://www.django-rest-framework.org/api-guide/authentication/

>Warning: Always use Django's standard login view when creating login pages. This will ensure your login views are properly protected.

> CSRF validation in REST framework works slightly differently to standard Django due to the need to support both session and non-session based authentication to the same views. This means that only authenticated requests require CSRF tokens, and anonymous requests may be sent without CSRF tokens. This behaviour is not suitable for login views, which should always have CSRF validation applied.

Login CSRF is explicitly outlined in owasp.org guidelines and should be addressed.
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#login-csrf

**Comment by iMerica** [comment]
Hi @ajbeach2, thanks for adding this issue. I'm going to run the test to try and reproduce it.

**Comment by ajbeach2** [comment]
I should clarify the issue here is the lack of csrf checks which is *potentially* vulnerable.

**Comment by iMerica** [comment]
I'm still thinking about this, but my initial reaction is that http 200 is actually the right response in this scenario. The Owasp notes on Login CSRF are unfortunately operating on some assumptions that don't map 1:1 to newer architectures (SPA-to-API).

I'm especially curious about this one:

> if an attacker uses CSRF to authenticate a victim on a shopping website using the attacker's account, and the victim then enters their credit card information, an attacker may be able to purchase items using the victim's stored card details

How exactly does that happen? How does the attacker get me to login using their details? Login is POST only so it can't be a malicious link click.

**Comment by iMerica** [comment]
Maybe we can expose a new setting called`LOGIN_HTTP_REFERRER_WHITE_LIST = ['example.com/']` for those who use the same host for the client and server, but also want to protect against malicious logins from third party sites? (similar to a same-origin policy)

**Comment by ajbeach2** [comment]
so this assumes that cross origin is misconfigured on the backend. Its much more difficult to do CSRF via ajax.  I don't know that this is a likely scenario, as i wasn't able to do a csrf with the default django settings.

But lets say i trick the user into going to my index.html.  The post request would return and set a cookie in the users browser with a session token. The user is then logged into an account I can control and i can redirect the user to http://mydomain.com. He uses the site, maybe enters in sensitive info. Because its an account i control, I can login myself.

```
// hosted on myevildomain.com
<!DOCTYPE html>
<html>
  <body>
    <script>
      window.onload = function() {
          var xmlhttp = new XMLHttpRequest();
          xmlhttp.open("POST", "http://mydomain.com/login/);
          xmlhttp.setRequestHeader("Content-Type", "text/plain;charset=UTF-8");
          xmlhttp.withCredentials = true;
          xmlhttp.send(JSON.stringify({"username":"david", "password":"password123"}));
    </script>
  </body>
</html>
```

The above would fail if using a double submit cookie, which django takes care of. In the case of SPA you have to read the that token form a cookie. https://docs.djangoproject.com/en/3.0/ref/csrf/#ajax

**Comment by ajbeach2** [comment]
I don't know that adding LOGIN_HTTP_REFERRER_WHITE_LIST is going to help. What is needed is to ensure that Django csrf middleware should be used in the same way as in django.contrib.auth.views package when dealing with web clients that use cookies for auth.

What i am doing in my SPA is just rewriting the forms/views provided in the django.contrib.auth and i keep all of the CSRF checks.  I use then separate url/views/auth for endpoints for the web client, and i have other url/views for non-web clients that use tokens.

Django rest disables csrf within the APIView class, so csrf checks are normally handled in rest_framework.authentication class, which by default will disable checks for unauthenticated users so you have to create a sub class and enable csrf checks for anonymous users.

So my solution looks something like this:

```python
class SessionAuthAll(SessionAuthentication):
    def authenticate(self, request):
        user = getattr(request._request, "user", None)
        if not getattr(request, "_dont_enforce_csrf_checks", False):
            self.enforce_csrf(request)

        return (user, None)

class LoginViewWeb(APIView):
    permission_classes = ()
    authentication_classes = (SessionAuthAll)

    @method_decorator(never_cache)
    @method_decorator(ensure_csrf_cookie)
    def dispatch(self, *args, **kwargs):
        return super(LoginView, self).dispatch(*args, **kwargs)
    
    def post(self, request, format=None):
        user = authenticate(
            request,
            username=request.data.get("username", None),
            password=request.data.get("password", None),
        )
        if user is None:
            return Response(
                {"error": {"login": ["Invalid username or password"]}},
                status=status.HTTP_401_UNAUTHORIZED,
            )

        login(request, user)
        return Response(
            {"authenticated": True, "user": UserSerializer(user).data},
            status.HTTP_200_OK,
        )
```

**Comment by iMerica** [comment]
Okay, I'm going to investigate this a bit more and maybe put together a PR that allows developers to enable CSRF protection on dj-rest-auth views (without breaking anything).

**Comment by alichass** [comment]
Hallo, I don't know if any moves have been made on this, but I hope that these links might offer something small to the discussion (though I realise they're not on the subject of login-type views in and of themselves, but on CSRF and jwt-cookie-auth on authenticated views):
https://security.stackexchange.com/questions/170388/do-i-need-csrf-token-if-im-using-bearer-jwt
https://security.stackexchange.com/questions/115766/is-a-jwt-usable-as-a-csrf-token

In summary it seems to me (and tbh quite a bit of the more detailed reads go right over my head)  that as long as any kind of automatic auth is  implemented, csrf tokens should also be used (even with REST_SESSION_LOGIN set to false, given that the jwt-cookie auth is happening automagically - perhaps im misunderstanding this). 

The go to solution seems to be to set a X-CSRFToken header along with any POST requests; though again, I realise its slightly different from the login problem, given that in that case its dealing with an unauthenticated user, rather than protecting a user from being tricked into sending an authenticated request. 

https://docs.djangoproject.com/en/3.0/ref/csrf/
Also worth looking at I think in regards to an ajax request. Turning it to false opens it up to XSS attacks, but at that point, you'd better hope the jwt-cookie is doing its job:
https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-CSRF_COOKIE_HTTPONLY

Sorry if this has all been discussed/dealt with already <3

**Comment by iMerica** [comment]
Closing this now that #103 has been merged. Thank you for raising this issue!

**Comment by efojs** [comment]
**TL;DR:** CSRF for login is good, would be happy if you tackle it, now have to workaround/customize.

Came here trying to wrap my head around CSRF protection. 
Reverse found that you have built in `enforce_csrf` mechanism.
But then I saw [`#True at your own risk` comment](https://github.com/iMerica/dj-rest-auth/blob/master/dj_rest_auth/jwt_auth.py#L126) and somehow came here

Because I use only `SessionAuthentication` https://github.com/iMerica/dj-rest-auth/pull/103 solution is not suitable for me (is it?).

So I ended up by subclassing `LoginView` (with help of https://stackoverflow.com/questions/49275069/):
```python
class CustomLoginView(LoginView):
    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        response = super(CustomLoginView, self).dispatch(*args, **kwargs)
        return response
```

and adding view that sets CSRF cookie on demand ([Django docs](https://docs.djangoproject.com/en/3.1/ref/csrf/#page-uses-ajax-without-any-html-form)):
```python
@ensure_csrf_cookie
def set_csrf_cookie(request):
    return JsonResponse({"detail": "CSRF cookie set"})
```

I have no solution how to improve https://github.com/iMerica/dj-rest-auth/pull/103 so it works for `SessionAuthentication` (because of lack of experience and it's very sensitive question)
Hope some day out-of-the-box solution will come

Also (have not dig deep to understand) why @alichass implemented and used [`get_csrf_cookie`](https://github.com/iMerica/dj-rest-auth/blob/master/dj_rest_auth/tests/urls.py#L72) path in tests, but didn't add it for production.
It would help SPAs in enforcement of CSRF protection.

#### Why bother?
1. DRF docs for SessionAuthentication clearly say that **login views** should tackle it: 
> **This behaviour is not suitable for login views, which should always have CSRF validation applied.** — [source](https://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication) 

2. https://en.wikipedia.org/wiki/Cross-site_request_forgery#Forging_login_requests
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#login-csrf
> An attacker may forge a request to log the victim into a target website using the attacker's credentials; this is known as login CSRF. Login CSRF makes various novel attacks possible; for instance, an attacker can later log into the site with his legitimate credentials and view private information like activity history that has been saved in the account. This attack has been demonstrated against Google[11] and Yahoo.[12]

3. (my inexperienced guess) it's possible for attacker to guess credentials via Timing Attack [such](https://codahale.com/a-lesson-in-timing-attacks/) or [such](https://www.idontplaydarts.com/2015/09/cross-domain-timing-attacks-against-lucene/), brutforce credentials or something like that..
