### ISSUE TITLE
Can't logout with JWT

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [jazzband/dj-rest-auth#96]
i try to logout with JWT but it give me the following error

```json
{
    "detail": "Refresh token was not included in request data."
}
```

i enabled blacklist b/c it say you need to enable cookie or blacklist so i did that. I set `REST_USE_JWT = True` but it given me the error above. But when i set `JWT_AUTH_COOKIE` the logout work, so am not sure if it is bug or this is how it should work

**Comment by iMerica** [comment]
Logout in applications that use JWT is a matter of removing the token from the client and optionally black-listing. 

Can you describe what behavior you're expecting?

**Comment by Mohamed-Kaizen** [comment]
when i set JWT_AUTH_COOKIE it does add it to the black list.But when unset JWT_AUTH_COOKIE it show the error above although am not using cookie in the application

**Comment by rwanito** [comment]
Hi !
I have the same problem.

I use /logout with the LogoutView but it doesn't have any effect.
I can still refresh token with my access token or access other page with my token. 
Is it normal ?

Thanks !

**Comment by brian-e-haley** [comment]
I am currently having the exact same issue and I posted on [r/django](https://www.reddit.com/r/django/comments/ih5rl9/django_rest_auth_simplejwt_logout_test_not/) to see if I was making a mistake here but it seems I was not. I wrote a test to confirm that a user would no longer be authorized to view their own user details since the token should have been removed from the db or flagged as no longer active.

Here is a test that should pass but currently does not:
``
class PositiveValidTestCase(APITestCase):
    @classmethod
    def setUpTestData(cls):
        pattern = re.compile(r'^.*email/(.*)/.*$',
                             re.DOTALL)
        cls.URL = reverse('rest_logout')
        cls.USER = {'username': 'user',
                    'email': 'user@name.ca',
                    'password1': 'complex_password',
                    'password2': 'complex_password'}
        client.post(reverse('rest_register'),
                    cls.USER)
        key = re.match(pattern, mail.outbox[0].body).group(1)
        client.post(reverse('account_email_verification_sent'),
                    {'key': key})

    def setUp(self):
        response = self.client.post(reverse('rest_login'),
                                    {'username': self.USER['username'],
                                    'password': self.USER['password1']})
        token = response.data['access_token']
        client.credentials(HTTP_AUTHORIZATION=f'Bearer {token}')

        self.RESPONSE = client.post(self.URL)

    def tearDown(self):
        client.credentials()

    def test_state(self):
        """
        After logging out a user should not be able to access their user
        details.
        """
        response = client.get(reverse('rest_user_details'))

        print(response.status_code, response.data)
        self.assertEqual(response.status_code,
                         status.HTTP_401_UNAUTHORIZED)
```
`test_state` currently returns a 200 response as well as the user details so it seems that when using JWT the logout route is currently not handling removing tokens.

**Comment by Popa-93** [comment]
Hi,
I had the same issue. Good news it is solved!

### Perimeter:
This issue concerns theJWT token management 
```
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'your-auth-cookie-name'

```
### Analyze
The functionality you are trying to use relies on two packages.
- dj-rest-auth, implements the Logout functionality and presents the Logout view.
- djangorestframework-simplejwt, implements the JSON Web Token authentication.

The target behavior on logout is to prevent access_token / refresh_token.
This is implemented as follow:

1. On all POST Logout calls, dj-rest-auth deletes local cookies.
2. JWT tokens cannot be invalided, but they can be blacklisted. If you have installed the application rest_framework_simplejwt.token_blacklist, dj-rest-auth will try to blacklist the refresh token.
Note: Access tokens are not blacklisted. From my understanding, their short lifetime limit the risks. I would appreciate to have your fedebacks on this.

Ok, so everything should work nicely, but there is a small problem between the two packages:
**djangorestframework-simplejwt does not accept token in stored in cookies**.
You can send them in the request's body but you will also want to keep your cookies secured with HttpOnly instruction.
So there is a 

In addition **dj-rest-auth** is deleting local cookies on logout, but it is also not managing JWT token in cookies correctly for refresh/verify.

### Solution
1. dj-rest-auth is managing JWT token in cookies for verify and refresh views. since version 2.1.1.
2. Awaiting fix on djangorestframework-simplejwt, @Wolf-Byte  suggested a workaround using middlewares to move date from head to body (#97 ):

```
from <your_project> import settings
from django.utils.deprecation import MiddlewareMixin
import json


class MoveJWTCookieIntoTheBody(MiddlewareMixin):
    """
    for Django Rest Framework JWT's POST "/token-refresh" endpoint --- check for a 'token' in the request.COOKIES
    and if, add it to the body payload.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        return response

    def process_view(self, request, view_func, *view_args, **view_kwargs):
        if request.path == '/auth/token/verify/' and settings.JWT_AUTH_COOKIE in request.COOKIES:

            if request.body != b'':
                data = json.loads(request.body)
                data['token'] = request.COOKIES[settings.JWT_AUTH_COOKIE]
                request._body = json.dumps(data).encode('utf-8')
            else:
                # I cannot create a body if it is not passed so the client must send '{}'
                pass

        return None

class MoveJWTRefreshCookieIntoTheBody(MiddlewareMixin):
    """
    for Django Rest Framework JWT's POST "/token-refresh" endpoint --- check for a 'token' in the request.COOKIES
    and if, add it to the body payload.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        return response

    def process_view(self, request, view_func, *view_args, **view_kwargs):
        if request.path == '/auth/token/refresh/' and settings.JWT_AUTH_REFRESH_COOKIE in request.COOKIES:

            if request.body != b'':
                data = json.loads(request.body)
                data['refresh'] = request.COOKIES[settings.JWT_AUTH_REFRESH_COOKIE]
                request._body = json.dumps(data).encode('utf-8')
            else:
                # I cannot create a body if it is not passed so the client must send '{}'
                pass

        return None
```
